logging:
  filename: null
  level: info
  format: '%(asctime)s | %(levelname)s | %(message)s'

ping:
  random_delay: 10
  interval: 30
  hosts:
    - www.google.de

speedtest:
  random_delay: 30
  interval: 120
  hosts:
    - d-speed.bi-host.net:8080
