logging:
  filename: null
  level: info
  format: '%(asctime)s | %(levelname)s | %(message)s'

ping:
  random_delay: 10
  interval: 30
  hosts:
    - www.google.de
    - www.kaitos.ai
    - 8.8.8.8
    - 192.168.1.1

